### ISSUE TITLE
Nasa nastran

### ISSUE THREAD

**Issue by pclausen** [legacycoderocks/awesome-legacy-code#11]
Great list. Please add a link to nastran.

https://github.com/nasa/NASTRAN-95

NASA Formula translator (NasTran) is the base of still used code (MSC Nastran and NX Nastran) for analyzing mainly structures (planes, rockets, trains, cars,...). [Fortran=Formula Translator]. See also https://en.m.wikipedia.org/wiki/Nastran

**Comment by mscottford** [comment]
Thanks a bunch for the suggestion @pclausen! I've added in it commit 9caca20.
